/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Exam: typeof import('./src/components/Exam.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Practice: typeof import('./src/components/Practice.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
